<a href="https://colab.research.google.com/github/salarbalou/Photothermal_Study_CQDs/blob/main/CQD_Characterization_UV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import plotly.io as pio
pio.templates.default  = 'plotly_white'
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.express as px
import scipy
from scipy import signal
from scipy.signal import find_peaks

In [2]:
CQDs = np.array(['Blue', 'Cyan', 'Green', 'Yellow', 'Orange', 'Red'])

In [ ]:
fig = make_subplots(rows = CQDs.size, cols = 1)
baseurl = 'https://raw.githubusercontent.com/salarbalou/Photothermal_Study_CQDs/main/'
char = '_CQD_FTIR.txt'
for i in range (CQDs.size):
 data = np.loadtxt(baseurl+CQDs[i]+char, delimiter = '\t')
 fig.add_trace(go.Scatter(x = data[:, 0], y = data[:, 1], mode  = 'lines', line_color = CQDs[i], name = f'{CQDs[i]}_CQD'), row  = i+1, col = 1)
 fig.update_layout(height = 1200, width = 1000)
 fig.update_xaxes(range = [3500, 500], title = 'wavelength(nm)', tickfont = dict(size = 12))
 fig.update_yaxes(range = [0, 100],  title = 'Transmittance (%)')
fig.show()

In [3]:
fig2 = make_subplots()
baseurlUV = 'https://raw.githubusercontent.com/salarbalou/Photothermal_Study_CQDs/main/'
charUV = '_CQD_UV.txt' 
charFL = '_CQD_FL.txt' 
multivalues = []
peaks_list = []
peaks_y_list = []
for i in range(CQDs.size):
 dataUV = np.loadtxt(baseurlUV+CQDs[i]+charUV, delimiter='\t')
 intent = dataUV[:, 1][dataUV[:, 0]> 600] = 0
 intent = dataUV[:, 1][dataUV[:, 0]>350]
 wave = dataUV[:, 0][dataUV[:, 0]>350]
 peaks = wave[np.argmax(intent)]
 peaks_list.append(peaks)
 peak = np.array(peaks_list)
 peaks_y = np.max(intent)
 peaks_y_list.append(peaks_y)
 peaky = np.array(peaks_y_list)
 text = peak[i]
 fig2.add_trace(go.Scatter(x = wave, y = signal.savgol_filter(intent, 53, 3), line_color = CQDs[i], name  = f'{CQDs[i]}_CQD Abs', mode = 'markers+lines', marker_color = 'rgba(100, 100, 100, 0)', showlegend = False))
 fig2.add_trace(go.Scatter(x = peak, y = peaky,     mode="markers+text",
                                                    marker_color = 'black',
                                                    marker_size = 8,
                                                    marker_opacity = 1,
                                                    name="Max Absorption",
                                                    text=np.round(peak, 1),  
                                                    textposition="top right", 
                                                    showlegend = False))
 fig2.update_xaxes(title = dict(text = 'Absorbance Wavelength (nm)', font = dict(size = 16)), ticks = 'outside', showgrid = False, showline = True, linecolor = 'black', range = [350, 600], nticks = 50, tickfont = dict(size = 14))
 fig2.update_yaxes(title = dict(text = 'Absorbance Intensity', font = dict(size = 16)),  ticks = 'outside', showgrid = False, showline = True, linecolor = 'black', range = [0, 0.7], tickfont = dict(size = 14), titlefont = dict(size=16))
 fig2.update_layout(height = 600, width = 1000)
fig2.show()

In [4]:
landa = peak*1e-9
h = 6.62e-34 #m^2.kg/s
c = 299792458 #m/s
nu = c/landa
E = np.round(h*nu*6.24e18, 2) #eV
print(np.round(peak, 2))
print(E)

[350.93 397.01 370.98 418.93 434.   407.98]
[3.53 3.12 3.34 2.96 2.85 3.04]


In [28]:
weight = np.array([1.9, 2.2, 2.8, 2.7, 3.2, 3.5])*1e-3 #g
v = 6e-3 #L
C = weight/v #mg/L
A = peaks_y_list
L = 1 #cm
e = A/C*L #L/mg.cm
print(f'Concentration: {np.round(C, 3)}')
print(np.round(e, 3))

Concentration: [0.317 0.367 0.467 0.45  0.533 0.583]
[1.108 1.215 0.536 0.968 0.383 0.987]


In [ ]:
fig3 = make_subplots(rows = 1, cols = 1)
datasUV = []
for i in range(CQDs.size):
 dataUV = np.loadtxt(baseurlUV+CQDs[i]+charUV, delimiter='\t')
 dataFL = np.loadtxt(baseurlUV+CQDs[i]+charFL, delimiter='\t')
 datasUV.append(dataUV)
 multivalue = 10/(np.max(datasUV[i][:, 1]))
 multivalues.append(multivalue)
 arrayofmv = np.array(multivalues)
 #datasUV[i] *= arrayofmv[i]
 fig3.add_trace(go.Scatter(x = datasUV[i][:, 0], y =datasUV[i][:, 1], mode = 'markers'), row = 1, col = 1)
 fig3.update_layout(height = 500, width = 2000)

In [187]:
figure = make_subplots()
datalist = []
for i in range(CQDs.size):
 dataFL = np.loadtxt(baseurlUV+CQDs[i]+charFL, delimiter='\t')
 datalist.append(dataFL)
 figure.add_scatter(x = dataFL[:, 0], y = dataFL[:, 1], mode = 'markers', marker_color = CQDs[i], name = f'{CQDs[i]}')
 figure.update_xaxes(range = [200, 800])
figure.show()

In [188]:
mv = []
for i in range(CQDs.size):
   mv.append(np.max(datalist[i][:, 1]))
mv = np.max(mv)/mv


In [189]:
newy = []
for i in range(CQDs.size):
  newdatalist = (datalist[i][:, 1])*mv[i]
  newy.append(newdatalist)

In [ ]:
newy

In [198]:
figure = make_subplots()
for i in range(CQDs.size):
 dataFL = np.loadtxt(baseurlUV+CQDs[i]+charFL, delimiter='\t')
 figure.add_trace(go.Scatter(x = dataFL[:, 0], y = signal.savgol_filter(newy[i], 53, 3), mode = 'lines', line_shape = 'spline', marker_color = CQDs[i], name = f'{CQDs[i]}'))
 figure.update_xaxes(range = [350, 680], title = 'Wavelenght (nm)', title_font = dict(size = 30), tickfont = dict(size = 16), showgrid = False, showline = True, linewidth = 3, linecolor = 'black', ticks = 'outside', nticks = 20)
 figure.update_yaxes(range = [20, 1000], title = dict(text = 'Fluorescennce Intensity (a.u.)', font = dict(size = 20)), title_font = dict(size  = 20), tickfont = dict(size = 16), showgrid = False, showline = True, linewidth = 3, linecolor = 'black', ticks = 'outside', nticks = 5)
 figure.update_layout(height = 600, width  = 1000)
figure.show()
# UV Curves were smoothed using Savitzky-Golay Filter